apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStoreName | default "ops360-secret-store" }}
  namespace: {{ .Values.namespace | default "ops360" }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | default "us-east-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName | default "ops360-secrets-sa" }}